In [1]:
import numpy as np
import  matplotlib.pyplot as plt

1. Create a numpy array of shape [9, 1] and fill it with random values.

In [2]:
arr = np.random.rand(9, 1)
arr

array([[0.83260858],
       [0.10685608],
       [0.76709498],
       [0.95843692],
       [0.46120334],
       [0.27633042],
       [0.53728614],
       [0.6903074 ],
       [0.45973653]])

2. Turn it into a 3 × 3 matrix.

In [3]:
mat = arr.reshape(3,3)
mat

array([[0.83260858, 0.10685608, 0.76709498],
       [0.95843692, 0.46120334, 0.27633042],
       [0.53728614, 0.6903074 , 0.45973653]])

3. Print the shape and type of the matrix.

In [4]:
print("Matrix Shape:", mat.shape)
print("Matrix Type:", type(mat))

Matrix Shape: (3, 3)
Matrix Type: <class 'numpy.ndarray'>


4. Get the first column of the matrix and multiply it by the third column of the matrix.

In [5]:
first_column = mat[:,0]
third_column = mat[:,2]
value = first_column @ third_column
value

1.1505452048655285

5. Create a new matrix of size [9, 9] and fill it with the value from the previous section.

In [6]:
new_mat = np.tile(value, (9,9))
new_mat

array([[1.1505452, 1.1505452, 1.1505452, 1.1505452, 1.1505452, 1.1505452,
        1.1505452, 1.1505452, 1.1505452],
       [1.1505452, 1.1505452, 1.1505452, 1.1505452, 1.1505452, 1.1505452,
        1.1505452, 1.1505452, 1.1505452],
       [1.1505452, 1.1505452, 1.1505452, 1.1505452, 1.1505452, 1.1505452,
        1.1505452, 1.1505452, 1.1505452],
       [1.1505452, 1.1505452, 1.1505452, 1.1505452, 1.1505452, 1.1505452,
        1.1505452, 1.1505452, 1.1505452],
       [1.1505452, 1.1505452, 1.1505452, 1.1505452, 1.1505452, 1.1505452,
        1.1505452, 1.1505452, 1.1505452],
       [1.1505452, 1.1505452, 1.1505452, 1.1505452, 1.1505452, 1.1505452,
        1.1505452, 1.1505452, 1.1505452],
       [1.1505452, 1.1505452, 1.1505452, 1.1505452, 1.1505452, 1.1505452,
        1.1505452, 1.1505452, 1.1505452],
       [1.1505452, 1.1505452, 1.1505452, 1.1505452, 1.1505452, 1.1505452,
        1.1505452, 1.1505452, 1.1505452],
       [1.1505452, 1.1505452, 1.1505452, 1.1505452, 1.1505452, 1.1505452

6. Create a new matrix of size [9, 9] and fill it with random values.

In [7]:
random_mat = np.random.rand(9,9)
random_mat

array([[0.62983687, 0.56704253, 0.21549677, 0.14780709, 0.36193787,
        0.48151825, 0.0871118 , 0.19899817, 0.14082204],
       [0.02284472, 0.35584064, 0.66968809, 0.38466931, 0.59469865,
        0.99499283, 0.6020251 , 0.12217705, 0.59956907],
       [0.23386894, 0.31346811, 0.21367375, 0.94251283, 0.22658937,
        0.21998533, 0.2872629 , 0.10808793, 0.02692558],
       [0.46456873, 0.50947743, 0.1913324 , 0.59325147, 0.71440023,
        0.84393411, 0.86982854, 0.20000049, 0.02733598],
       [0.94168341, 0.4767003 , 0.98714832, 0.73339018, 0.14967572,
        0.63254732, 0.64662681, 0.24103421, 0.53342605],
       [0.13293596, 0.22528108, 0.79130127, 0.11755997, 0.66589823,
        0.48326029, 0.25198296, 0.88762679, 0.6376232 ],
       [0.90039555, 0.26658706, 0.14626672, 0.07541214, 0.85404734,
        0.19066866, 0.52006736, 0.41093315, 0.1745076 ],
       [0.2550051 , 0.30813321, 0.3269348 , 0.575349  , 0.86021945,
        0.68395552, 0.51222236, 0.55938583, 0.33271331],


7. Stack the two matrices along a new dimension to form a tensor of shape [9, 9, 2].

In [8]:
tensor = np.stack([new_mat, random_mat], axis=2)
tensor

array([[[1.1505452 , 0.62983687],
        [1.1505452 , 0.56704253],
        [1.1505452 , 0.21549677],
        [1.1505452 , 0.14780709],
        [1.1505452 , 0.36193787],
        [1.1505452 , 0.48151825],
        [1.1505452 , 0.0871118 ],
        [1.1505452 , 0.19899817],
        [1.1505452 , 0.14082204]],

       [[1.1505452 , 0.02284472],
        [1.1505452 , 0.35584064],
        [1.1505452 , 0.66968809],
        [1.1505452 , 0.38466931],
        [1.1505452 , 0.59469865],
        [1.1505452 , 0.99499283],
        [1.1505452 , 0.6020251 ],
        [1.1505452 , 0.12217705],
        [1.1505452 , 0.59956907]],

       [[1.1505452 , 0.23386894],
        [1.1505452 , 0.31346811],
        [1.1505452 , 0.21367375],
        [1.1505452 , 0.94251283],
        [1.1505452 , 0.22658937],
        [1.1505452 , 0.21998533],
        [1.1505452 , 0.2872629 ],
        [1.1505452 , 0.10808793],
        [1.1505452 , 0.02692558]],

       [[1.1505452 , 0.46456873],
        [1.1505452 , 0.50947743],
        

8. Get the mean, sum, and standard deviation of the new matrices along the third dimension.

In [9]:
mean_tensor = np.mean(tensor, axis=2)
sum_tensor = np.sum(tensor, axis=2)
std_tensor = np.std(tensor, axis=2)
print('mean_tensor \n', mean_tensor)
print('sum_tensor \n', sum_tensor)
print('std_tensor \n', std_tensor)

mean_tensor 
 [[0.89019104 0.85879387 0.68302099 0.64917615 0.75624154 0.81603173
  0.6188285  0.67477169 0.64568362]
 [0.58669496 0.75319292 0.91011665 0.76760726 0.87262193 1.07276902
  0.87628515 0.63636113 0.87505714]
 [0.69220707 0.73200666 0.68210948 1.04652902 0.68856729 0.68526527
  0.71890405 0.62931657 0.58873539]
 [0.80755697 0.83001132 0.6709388  0.87189834 0.93247272 0.99723966
  1.01018687 0.67527285 0.58894059]
 [1.04611431 0.81362275 1.06884676 0.94196769 0.65011046 0.89154626
  0.89858601 0.69578971 0.84198563]
 [0.64174058 0.68791314 0.97092324 0.63405259 0.90822172 0.81690275
  0.70126408 1.019086   0.8940842 ]
 [1.02547038 0.70856613 0.64840596 0.61297867 1.00229627 0.67060693
  0.83530628 0.78073918 0.6625264 ]
 [0.70277515 0.72933921 0.73874    0.8629471  1.00538233 0.91725036
  0.83138378 0.85496552 0.74162926]
 [0.84132541 0.71465731 0.84945662 1.06911421 0.97150306 0.58993093
  0.78295938 0.8094055  0.86736583]]
sum_tensor 
 [[1.78038208 1.71758773 1.36604197 1

9. Get all the indices of the array for which the value is greater than the mean.

In [10]:
arr_mean = np.mean(arr)
print(arr)
print(arr_mean)
indices_greater_than_mean = np.where(arr > np.mean(arr))
indices_greater_than_mean

[[0.83260858]
 [0.10685608]
 [0.76709498]
 [0.95843692]
 [0.46120334]
 [0.27633042]
 [0.53728614]
 [0.6903074 ]
 [0.45973653]]
0.5655400432118686


(array([0, 2, 3, 7]), array([0, 0, 0, 0]))

10. Replaces the values of items in these indices by 0.


In [11]:
arr[indices_greater_than_mean] = 0
arr 

array([[0.        ],
       [0.10685608],
       [0.        ],
       [0.        ],
       [0.46120334],
       [0.27633042],
       [0.53728614],
       [0.        ],
       [0.45973653]])

11. Now, let’s benchmark vectorized numpy operations and see that they are actually faster.

1. Create two random tensors of shape 512 × 512 × 3

In [12]:
tensor_a = np.random.rand(512, 512, 3)
tensor_b = np.random.rand(512, 512, 3)

2. Multiply the two matrices, perform the multiplication once using numpy operations and once using
a regular python loop.

In [13]:
def numpy_multiplication():
    result = np.multiply(tensor_a, tensor_b)

def python_loop_multiplication():
    result = np.zeros_like(tensor_a)
    for i in range(tensor_a.shape[0]):
        for j in range(tensor_a.shape[1]):
            for k in range(tensor_a.shape[2]):
                result[i, j, k] = tensor_a[i, j, k] * tensor_b[i, j, k]


3. Repeat this 1000 times (this can be in a loop)

In [14]:
import timeit

4. Time each of the multiplication methods to see what is faster

In [15]:
num_repeats = 1000
numpy_time = timeit.timeit(numpy_multiplication, number=num_repeats)
python_loop_time = timeit.timeit(python_loop_multiplication, number=num_repeats)

print(f"Numpy Multiplication Time: {numpy_time:.6f} seconds")
print(f"Python Loop Multiplication Time: {python_loop_time:.6f} seconds")

Numpy Multiplication Time: 0.581290 seconds
Python Loop Multiplication Time: 224.057724 seconds
