In [1]:
import numpy as np
import  matplotlib.pyplot as plt

1. Create a numpy array of shape [9, 1] and fill it with random values.

In [2]:
arr = np.random.rand(9, 1)
arr

array([[0.93124426],
       [0.68043749],
       [0.69487052],
       [0.05134152],
       [0.97108857],
       [0.07861027],
       [0.4835629 ],
       [0.48677352],
       [0.02416514]])

2. Turn it into a 3 × 3 matrix.

In [3]:
mat = arr.reshape(3,3)
mat

array([[0.93124426, 0.68043749, 0.69487052],
       [0.05134152, 0.97108857, 0.07861027],
       [0.4835629 , 0.48677352, 0.02416514]])

3. Print the shape and type of the matrix.

In [4]:
print("Matrix Shape:", mat.shape)
print("Matrix Type:", type(mat))

Matrix Shape: (3, 3)
Matrix Type: <class 'numpy.ndarray'>


4. Get the first column of the matrix and multiply it by the third column of the matrix.

In [5]:
first_column = mat[:,0]
third_column = mat[:,2]
value = first_column @ third_column
value

0.662815517581623

5. Create a new matrix of size [9, 9] and fill it with the value from the previous section.

In [6]:
new_mat = np.tile(value, (9,9))
new_mat

array([[0.66281552, 0.66281552, 0.66281552, 0.66281552, 0.66281552,
        0.66281552, 0.66281552, 0.66281552, 0.66281552],
       [0.66281552, 0.66281552, 0.66281552, 0.66281552, 0.66281552,
        0.66281552, 0.66281552, 0.66281552, 0.66281552],
       [0.66281552, 0.66281552, 0.66281552, 0.66281552, 0.66281552,
        0.66281552, 0.66281552, 0.66281552, 0.66281552],
       [0.66281552, 0.66281552, 0.66281552, 0.66281552, 0.66281552,
        0.66281552, 0.66281552, 0.66281552, 0.66281552],
       [0.66281552, 0.66281552, 0.66281552, 0.66281552, 0.66281552,
        0.66281552, 0.66281552, 0.66281552, 0.66281552],
       [0.66281552, 0.66281552, 0.66281552, 0.66281552, 0.66281552,
        0.66281552, 0.66281552, 0.66281552, 0.66281552],
       [0.66281552, 0.66281552, 0.66281552, 0.66281552, 0.66281552,
        0.66281552, 0.66281552, 0.66281552, 0.66281552],
       [0.66281552, 0.66281552, 0.66281552, 0.66281552, 0.66281552,
        0.66281552, 0.66281552, 0.66281552, 0.66281552],


6. Create a new matrix of size [9, 9] and fill it with random values.

In [7]:
random_mat = np.random.rand(9,9)
random_mat

array([[7.44697406e-01, 6.11090270e-01, 6.37479957e-01, 3.08114493e-01,
        6.63806330e-02, 6.16915498e-01, 3.65940410e-01, 4.57779672e-01,
        3.57571627e-01],
       [7.28544140e-01, 9.02142681e-01, 4.97096739e-01, 3.81307697e-02,
        9.21313983e-01, 9.19977390e-01, 5.22468434e-01, 9.67965004e-01,
        8.26043166e-01],
       [6.78621959e-01, 2.97675007e-01, 5.70046586e-01, 8.05228003e-01,
        5.47648519e-01, 1.16775519e-01, 2.08109417e-01, 2.39045199e-01,
        3.99535806e-01],
       [3.38197306e-01, 4.87057752e-01, 6.63489957e-01, 6.01054032e-01,
        6.38146477e-01, 8.21519363e-01, 5.80932999e-01, 9.73511809e-01,
        6.86813657e-01],
       [2.45521242e-01, 9.78460439e-01, 4.01821198e-01, 2.87272652e-01,
        7.22902044e-01, 7.82299485e-01, 9.73325435e-01, 2.98633743e-01,
        1.18480469e-01],
       [4.45690269e-01, 5.53418195e-01, 7.68472593e-01, 3.29687940e-01,
        8.13106065e-01, 7.46023809e-01, 8.28473916e-01, 9.54377987e-01,
        5.4

7. Stack the two matrices along a new dimension to form a tensor of shape [9, 9, 2].

In [8]:
tensor = np.stack([new_mat, random_mat], axis=2)
tensor

array([[[6.62815518e-01, 7.44697406e-01],
        [6.62815518e-01, 6.11090270e-01],
        [6.62815518e-01, 6.37479957e-01],
        [6.62815518e-01, 3.08114493e-01],
        [6.62815518e-01, 6.63806330e-02],
        [6.62815518e-01, 6.16915498e-01],
        [6.62815518e-01, 3.65940410e-01],
        [6.62815518e-01, 4.57779672e-01],
        [6.62815518e-01, 3.57571627e-01]],

       [[6.62815518e-01, 7.28544140e-01],
        [6.62815518e-01, 9.02142681e-01],
        [6.62815518e-01, 4.97096739e-01],
        [6.62815518e-01, 3.81307697e-02],
        [6.62815518e-01, 9.21313983e-01],
        [6.62815518e-01, 9.19977390e-01],
        [6.62815518e-01, 5.22468434e-01],
        [6.62815518e-01, 9.67965004e-01],
        [6.62815518e-01, 8.26043166e-01]],

       [[6.62815518e-01, 6.78621959e-01],
        [6.62815518e-01, 2.97675007e-01],
        [6.62815518e-01, 5.70046586e-01],
        [6.62815518e-01, 8.05228003e-01],
        [6.62815518e-01, 5.47648519e-01],
        [6.62815518e-01, 1.167

8. Get the mean, sum, and standard deviation of the new matrices along the third dimension.

In [9]:
mean_tensor = np.mean(tensor, axis=2)
sum_tensor = np.sum(tensor, axis=2)
std_tensor = np.std(tensor, axis=2)
print('mean_tensor \n', mean_tensor)
print('sum_tensor \n', sum_tensor)
print('std_tensor \n', std_tensor)

mean_tensor 
 [[0.70375646 0.63695289 0.65014774 0.48546501 0.36459808 0.63986551
  0.51437796 0.5602976  0.51019357]
 [0.69567983 0.7824791  0.57995613 0.35047314 0.79206475 0.79139645
  0.59264198 0.81539026 0.74442934]
 [0.67071874 0.48024526 0.61643105 0.73402176 0.60523202 0.38979552
  0.43546247 0.45093036 0.53117566]
 [0.50050641 0.57493663 0.66315274 0.63193477 0.650481   0.74216744
  0.62187426 0.81816366 0.67481459]
 [0.45416838 0.82063798 0.53231836 0.47504408 0.69285878 0.7225575
  0.81807048 0.48072463 0.39064799]
 [0.55425289 0.60811686 0.71564406 0.49625173 0.73796079 0.70441966
  0.74564472 0.80859675 0.6040927 ]
 [0.57504488 0.77398161 0.69123976 0.43897836 0.41669974 0.72052309
  0.58616227 0.74594436 0.39150373]
 [0.7728019  0.50950331 0.50203071 0.60188625 0.37905701 0.65958632
  0.69301651 0.7739693  0.69188067]
 [0.69258404 0.60588892 0.65998704 0.56972004 0.52974226 0.80319389
  0.33150698 0.44021851 0.75514246]]
sum_tensor 
 [[1.40751292 1.27390579 1.30029547 0.

9. Get all the indices of the array for which the value is greater than the mean.

In [10]:
arr_mean = np.mean(arr)
print(arr)
print(arr_mean)
indices_greater_than_mean = np.where(arr > np.mean(arr))
indices_greater_than_mean

[[0.93124426]
 [0.68043749]
 [0.69487052]
 [0.05134152]
 [0.97108857]
 [0.07861027]
 [0.4835629 ]
 [0.48677352]
 [0.02416514]]
0.4891215759252964


(array([0, 1, 2, 4]), array([0, 0, 0, 0]))

10. Replaces the values of items in these indices by 0.


In [11]:
arr[indices_greater_than_mean] = 0
arr 

array([[0.        ],
       [0.        ],
       [0.        ],
       [0.05134152],
       [0.        ],
       [0.07861027],
       [0.4835629 ],
       [0.48677352],
       [0.02416514]])

11. Now, let’s benchmark vectorized numpy operations and see that they are actually faster.

1. Create two random tensors of shape 512 × 512 × 3

In [12]:
tensor_a = np.random.rand(512, 512, 3)
tensor_b = np.random.rand(512, 512, 3)

2. Multiply the two matrices, perform the multiplication once using numpy operations and once using
a regular python loop.

In [13]:
def numpy_multiplication():
    result = np.multiply(tensor_a, tensor_b)

def python_loop_multiplication():
    result = np.zeros_like(tensor_a)
    for i in range(tensor_a.shape[0]):
        for j in range(tensor_a.shape[1]):
            for k in range(tensor_a.shape[2]):
                result[i, j, k] = tensor_a[i, j, k] * tensor_b[i, j, k]


3. Repeat this 1000 times (this can be in a loop)

In [14]:
import timeit

4. Time each of the multiplication methods to see what is faster

In [15]:
num_repeats = 1000
numpy_time = timeit.timeit(numpy_multiplication, number=num_repeats)
python_loop_time = timeit.timeit(python_loop_multiplication, number=num_repeats)

print(f"Numpy Multiplication Time: {numpy_time:.6f} seconds")
print(f"Python Loop Multiplication Time: {python_loop_time:.6f} seconds")

Numpy Multiplication Time: 0.734017 seconds
Python Loop Multiplication Time: 225.965089 seconds
