In [1]:
import numpy as np
import  matplotlib.pyplot as plt

1. Create a numpy array of shape [9, 1] and fill it with random values.

In [2]:
arr = np.random.rand(9, 1)
arr

array([[0.54021443],
       [0.54922638],
       [0.78433846],
       [0.1256529 ],
       [0.10852926],
       [0.82307774],
       [0.92759067],
       [0.12331779],
       [0.44947313]])

2. Turn it into a 3 × 3 matrix.

In [3]:
mat = arr.reshape(3,3)
mat

array([[0.54021443, 0.54922638, 0.78433846],
       [0.1256529 , 0.10852926, 0.82307774],
       [0.92759067, 0.12331779, 0.44947313]])

3. Print the shape and type of the matrix.

In [4]:
print("Matrix Shape:", mat.shape)
print("Matrix Type:", type(mat))

Matrix Shape: (3, 3)
Matrix Type: <class 'numpy.ndarray'>


4. Get the first column of the matrix and multiply it by the third column of the matrix.

In [5]:
first_column = mat[:,0]
third_column = mat[:,2]
value = first_column @ third_column
value

0.9440601369846486

5. Create a new matrix of size [9, 9] and fill it with the value from the previous section.

In [6]:
new_mat = np.tile(value, (9,9))
new_mat

array([[0.94406014, 0.94406014, 0.94406014, 0.94406014, 0.94406014,
        0.94406014, 0.94406014, 0.94406014, 0.94406014],
       [0.94406014, 0.94406014, 0.94406014, 0.94406014, 0.94406014,
        0.94406014, 0.94406014, 0.94406014, 0.94406014],
       [0.94406014, 0.94406014, 0.94406014, 0.94406014, 0.94406014,
        0.94406014, 0.94406014, 0.94406014, 0.94406014],
       [0.94406014, 0.94406014, 0.94406014, 0.94406014, 0.94406014,
        0.94406014, 0.94406014, 0.94406014, 0.94406014],
       [0.94406014, 0.94406014, 0.94406014, 0.94406014, 0.94406014,
        0.94406014, 0.94406014, 0.94406014, 0.94406014],
       [0.94406014, 0.94406014, 0.94406014, 0.94406014, 0.94406014,
        0.94406014, 0.94406014, 0.94406014, 0.94406014],
       [0.94406014, 0.94406014, 0.94406014, 0.94406014, 0.94406014,
        0.94406014, 0.94406014, 0.94406014, 0.94406014],
       [0.94406014, 0.94406014, 0.94406014, 0.94406014, 0.94406014,
        0.94406014, 0.94406014, 0.94406014, 0.94406014],


6. Create a new matrix of size [9, 9] and fill it with random values.

In [7]:
random_mat = np.random.rand(9,9)
random_mat

array([[0.43821769, 0.04356196, 0.4836324 , 0.89522323, 0.60100748,
        0.39719864, 0.97805568, 0.20232325, 0.39615048],
       [0.52753434, 0.95152427, 0.86160458, 0.53679587, 0.39685626,
        0.62263291, 0.01492684, 0.27131909, 0.32033106],
       [0.74528048, 0.32950387, 0.70255297, 0.6972777 , 0.30709271,
        0.36778573, 0.68306663, 0.31198225, 0.37845452],
       [0.81302953, 0.50871026, 0.42534121, 0.14779481, 0.02088415,
        0.04436031, 0.83031677, 0.50490064, 0.09898121],
       [0.41402752, 0.79502199, 0.46034213, 0.08964967, 0.9825416 ,
        0.93563315, 0.40351079, 0.12200439, 0.76212225],
       [0.11156276, 0.56451477, 0.47418467, 0.31227893, 0.38582548,
        0.96065499, 0.26237547, 0.80320903, 0.35530449],
       [0.9581677 , 0.8028129 , 0.67935868, 0.12458173, 0.14168307,
        0.06946184, 0.25097508, 0.05910105, 0.52668139],
       [0.289264  , 0.608538  , 0.53475153, 0.82536391, 0.20394404,
        0.872322  , 0.04993114, 0.4234784 , 0.03063121],


7. Stack the two matrices along a new dimension to form a tensor of shape [9, 9, 2].

In [8]:
tensor = np.stack([new_mat, random_mat], axis=2)
tensor

array([[[0.94406014, 0.43821769],
        [0.94406014, 0.04356196],
        [0.94406014, 0.4836324 ],
        [0.94406014, 0.89522323],
        [0.94406014, 0.60100748],
        [0.94406014, 0.39719864],
        [0.94406014, 0.97805568],
        [0.94406014, 0.20232325],
        [0.94406014, 0.39615048]],

       [[0.94406014, 0.52753434],
        [0.94406014, 0.95152427],
        [0.94406014, 0.86160458],
        [0.94406014, 0.53679587],
        [0.94406014, 0.39685626],
        [0.94406014, 0.62263291],
        [0.94406014, 0.01492684],
        [0.94406014, 0.27131909],
        [0.94406014, 0.32033106]],

       [[0.94406014, 0.74528048],
        [0.94406014, 0.32950387],
        [0.94406014, 0.70255297],
        [0.94406014, 0.6972777 ],
        [0.94406014, 0.30709271],
        [0.94406014, 0.36778573],
        [0.94406014, 0.68306663],
        [0.94406014, 0.31198225],
        [0.94406014, 0.37845452]],

       [[0.94406014, 0.81302953],
        [0.94406014, 0.50871026],
        

8. Get the mean, sum, and standard deviation of the new matrices along the third dimension.

In [9]:
mean_tensor = np.mean(tensor, axis=2)
sum_tensor = np.sum(tensor, axis=2)
std_tensor = np.std(tensor, axis=2)
print('mean_tensor \n', mean_tensor)
print('sum_tensor \n', sum_tensor)
print('std_tensor \n', std_tensor)

mean_tensor 
 [[0.69113891 0.49381105 0.71384627 0.91964169 0.77253381 0.67062939
  0.96105791 0.57319169 0.67010531]
 [0.73579724 0.9477922  0.90283236 0.740428   0.6704582  0.78334653
  0.47949349 0.60768961 0.6321956 ]
 [0.84467031 0.636782   0.82330655 0.82066892 0.62557642 0.65592294
  0.81356338 0.62802119 0.66125733]
 [0.87854483 0.7263852  0.68470067 0.54592747 0.48247214 0.49421022
  0.88718845 0.72448039 0.52152068]
 [0.67904383 0.86954107 0.70220113 0.5168549  0.96330087 0.93984664
  0.67378546 0.53303226 0.8530912 ]
 [0.52781145 0.75428745 0.7091224  0.62816953 0.66494281 0.95235756
  0.6032178  0.87363459 0.64968232]
 [0.95111392 0.87343652 0.81170941 0.53432093 0.54287161 0.50676099
  0.59751761 0.5015806  0.73537076]
 [0.61666207 0.77629907 0.73940583 0.88471202 0.57400209 0.90819107
  0.49699564 0.68376927 0.48734568]
 [0.81325524 0.47895779 0.78628281 0.93845111 0.86480451 0.53417168
  0.91408104 0.80845726 0.64089082]]
sum_tensor 
 [[1.38227783 0.9876221  1.42769254 1

9. Get all the indices of the array for which the value is greater than the mean.

In [10]:
arr_mean = np.mean(arr)
print(arr)
print(arr_mean)
indices_greater_than_mean = np.where(arr > np.mean(arr))
indices_greater_than_mean

[[0.54021443]
 [0.54922638]
 [0.78433846]
 [0.1256529 ]
 [0.10852926]
 [0.82307774]
 [0.92759067]
 [0.12331779]
 [0.44947313]]
0.49238008375369813


(array([0, 1, 2, 5, 6]), array([0, 0, 0, 0, 0]))

10. Replaces the values of items in these indices by 0.


In [11]:
arr[indices_greater_than_mean] = 0
arr 

array([[0.        ],
       [0.        ],
       [0.        ],
       [0.1256529 ],
       [0.10852926],
       [0.        ],
       [0.        ],
       [0.12331779],
       [0.44947313]])

11. Now, let’s benchmark vectorized numpy operations and see that they are actually faster.

1. Create two random tensors of shape 512 × 512 × 3

In [12]:
tensor_a = np.random.rand(512, 512, 3)
tensor_b = np.random.rand(512, 512, 3)

2. Multiply the two matrices, perform the multiplication once using numpy operations and once using
a regular python loop.

In [13]:
def numpy_multiplication():
    result = np.multiply(tensor_a, tensor_b)

def python_loop_multiplication():
    result = np.zeros_like(tensor_a)
    for i in range(tensor_a.shape[0]):
        for j in range(tensor_a.shape[1]):
            for k in range(tensor_a.shape[2]):
                result[i, j, k] = tensor_a[i, j, k] * tensor_b[i, j, k]


3. Repeat this 1000 times (this can be in a loop)

In [14]:
import timeit

4. Time each of the multiplication methods to see what is faster

In [ ]:
num_repeats = 1000
numpy_time = timeit.timeit(numpy_multiplication, number=num_repeats)
python_loop_time = timeit.timeit(python_loop_multiplication, number=num_repeats)

print(f"Numpy Multiplication Time: {numpy_time:.6f} seconds")
print(f"Python Loop Multiplication Time: {python_loop_time:.6f} seconds")